apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-frontend
  template:
    metadata:
      labels:
        app: booking-frontend
    spec:
      containers:
        - name: booking-frontend
          image: mladenv7/booking-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4200
---