apiVersion: v1
kind: Service
metadata:
  name: booking-frontend
spec:
  type: LoadBalancer
  selector:
    app: booking-frontend
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 31000