apiVersion: v1
kind: Service
metadata:
  name: booking-frontend
spec:
  type: NodePort
  selector:
    app: booking-frontend
  ports:
    - port: 4200
      protocol: TCP
      targetPort: 4200
      nodePort: 31000