apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: {{ .Values.nodePort }}